In [0]:
import numpy as np 

In [12]:
a=np.array([1,2,3],dtype='int8')
a

array([1, 2, 3], dtype=int8)

In [5]:
b=np.array([[1,2,3],[4.1,5.1,6.2]])
b

array([[1. , 2. , 3. ],
       [4.1, 5.1, 6.2]])

In [6]:
a.ndim

1

In [7]:
b.ndim

2

In [8]:
a.shape

(3,)

In [9]:
b.shape

(2, 3)

In [13]:
a.dtype

dtype('int8')

In [11]:
b.dtype

dtype('float64')

In [14]:
a.size

3

In [15]:
a.itemsize

1

In [16]:
a.nbytes

3

In [19]:
b[1][1]

5.1

In [20]:
b[1,1]

5.1

In [25]:
b[0,:]

array([1., 2., 3.])

In [26]:
b[:,2]

array([3. , 6.2])

In [27]:
np.zeros(6)

array([0., 0., 0., 0., 0., 0.])

In [29]:
np.zeros((3,3,3))

array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]])

ERROR! Session/line number was not unique in database. History logging moved to new session 59


In [31]:
np.ones(10,dtype='int8')

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1], dtype=int8)

In [32]:
np.full((2,2),99) 

array([[99, 99],
       [99, 99]])

In [33]:
np.full_like(b,4)

array([[4., 4., 4.],
       [4., 4., 4.]])

In [34]:
np.random.rand(2,3 )

array([[0.87744307, 0.75519416, 0.51415535],
       [0.4617363 , 0.87736448, 0.00731289]])

In [36]:
np.random.random_sample(b.shape)

array([[0.58174662, 0.99898025, 0.91930771],
       [0.44086438, 0.43630204, 0.58862657]])

In [41]:
np.random.randint(5,10,size=(8,))

array([6, 8, 9, 7, 7, 7, 9, 9])

In [42]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [43]:
np.identity(2)

array([[1., 0.],
       [0., 1.]])

In [46]:
a=np.random.randint(1,5,size=(1,5))
a

array([[2, 3, 3, 2, 4]])

In [52]:
r=np.repeat(a,3)
r

array([2, 2, 2, 3, 3, 3, 3, 3, 3, 2, 2, 2, 4, 4, 4])

In [54]:
r=np.repeat(a,3,axis=0)
r

array([[2, 3, 3, 2, 4],
       [2, 3, 3, 2, 4],
       [2, 3, 3, 2, 4]])

In [57]:
r=np.repeat(a,2,axis=1)
r

array([[2, 2, 3, 3, 3, 3, 2, 2, 4, 4]])

In [59]:
a=np.zeros((5,5))
a

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [61]:
a[0],a[4],a[:,0],a[:,4]=1,1,1,1
a

array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])

In [64]:
a[2,2]=9
a

array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 9., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])

In [66]:
a=np.full((3,3),7)
a

array([[7, 7, 7],
       [7, 7, 7],
       [7, 7, 7]])

In [68]:
b=a.copy()
b


array([[7, 7, 7],
       [7, 7, 7],
       [7, 7, 7]])

In [69]:
a=np.array([1,2,3,4])
a

array([1, 2, 3, 4])

In [70]:
a+2

array([3, 4, 5, 6])

In [73]:
a-2

array([-1,  0,  1,  2])

In [74]:
b=np.array([1,2,1,2])
a+b

array([2, 4, 4, 6])

In [75]:
np.sin(a)

array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 ])

In [76]:
np.cos(a )

array([ 0.54030231, -0.41614684, -0.9899925 , -0.65364362])

In [78]:
 a=np.ones((3,3))
 a


array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [80]:
b=np.full(shape=(3,2),fill_value=8)
b

array([[8, 8],
       [8, 8],
       [8, 8]])

In [81]:
np.matmul(a,b)

array([[24., 24.],
       [24., 24.],
       [24., 24.]])

In [83]:
x=np.identity(3)
x

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [85]:
np.linalg.det(x)

1.0

In [86]:
np.transpose(a)

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [92]:
np.linalg.inv(x)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [95]:
m=np.random.rand(2,3)

<function ndarray.mean>

In [96]:
np.mean(m)

0.4960063738724441

In [97]:
np.min(m)

0.025962337223659038

In [98]:
np.max(m)

0.8246601412804291

In [99]:
np.min(m,axis=0)

array([0.02596234, 0.68054767, 0.23885377])

In [100]:
m

array([[0.51374115, 0.68054767, 0.82466014],
       [0.02596234, 0.69227318, 0.23885377]])

In [101]:
np.max(m,axis=1)

array([0.82466014, 0.69227318])

In [102]:
np.sum(m)

2.976038243234665

In [105]:
a=np.random.randint(1,10,size=(2,4))
a

array([[3, 7, 1, 7],
       [2, 9, 9, 4]])

In [107]:
a.reshape(2,4)

array([[3, 7, 1, 7],
       [2, 9, 9, 4]])

In [108]:
a.reshape(4,-1)

array([[3, 7],
       [1, 7],
       [2, 9],
       [9, 4]])

In [0]:
a.reshape(8)

array([3, 7, 1, 7, 2, 9, 9, 4])

In [113]:
a=np.array([1,2,3,4])
b=np.array([5,6,7,8])
c=np.vstack([a,b])
c 

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [114]:
c>5

array([[False, False, False, False],
       [False,  True,  True,  True]])

In [115]:
 c[c>5]

array([6, 7, 8])

In [118]:
np.any(c>6,axis=0)

array([False, False,  True,  True])

In [119]:
np.all(c>6,axis=0)

array([False, False, False, False])